### PR TITLE
fix: use go-ipfs.version from parent package.json

### LINKED ISSUE #33: Check for a "go-ipfs" property in the parent project
From the docs, I assume I should be able to set a `go-ipfs` property in the package.json of a project that depends on go-ipfs-dep, but from the code, it looks like it will always check for a `go-ipfs` property on it's own package.json and nowhere else.

`pkg` is this projects package.json
https://github.com/ipfs/npm-go-ipfs-dep/blob/363d0273f3d34fb3038dcde66e79dffc9b3a4bdf/src/index.js#L28

and later we check it for a `go-ipfs` property
https://github.com/ipfs/npm-go-ipfs-dep/blob/363d0273f3d34fb3038dcde66e79dffc9b3a4bdf/src/index.js#L62

I'm assuming that's a bug, as I can't think of a use case for needing to set that for _this_ package.

### PR DESCRIPTION
**Pull request by olizilla**
- use [pkg-conf](https://github.com/sindresorhus/pkg-conf#readme) to fetch `go-ipfs` config from a parent package.json rather than checking for it in _this_ modules package.json
- add test to check `go-ipfs.version` is used during npm install

fixes #33

License: MIT
Signed-off-by: Oli Evans <oli@tableflip.io>

### CODE REVIEW

**Comment by hacdias** [comment]
@alanshaw could you take a look at this and perhaps release it, please? 😃

File: src/index.js [hunk 1]
```diff
@@ -55,22 +56,19 @@ async function download ({ installPath, url }) {
...
-
-  const goIpfsVersion = (goIpfsInfo && goIpfsInfo.version)
-    ? pkg['go-ipfs'].version
-    : 'v' + pkg.version.replace(/-[0-9]+/, '')
-
-  const distUrl = (goIpfsInfo && goIpfsInfo.distUrl)
-    ? pkg['go-ipfs'].distUrl
-    : 'https://dist.ipfs.io'
-
+async function cleanArguments (version, platform, arch, installPath) {
```
Comment (alanshaw) [inline src/index.js]: Note async currently - using `pkgConf.sync`.

File: test/install.js [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+  } catch (err) {
+    console.error(err)
+  }
+}
+
+test.onFinish(() => {
+  fs.unlinkSync(path.join(__dirname, tarballName))
+})
+
+test('Ensure go-ipfs.version defined in parent package.json is used', async (t) => {
```
Comment (alanshaw) [inline test/install.js]: Also not async! 😄

File: test/install.js [hunk 3]
```diff
@@ -0,0 +1,43 @@
...
+  try {
+    const parentDir = path.join(__dirname, '..')
+    const res = execa.sync('npm', ['pack', parentDir], {
+      cwd: __dirname
+    })
+    tarballName = res.stdout
+    return tarballName
+  } catch (err) {
+    console.error(err)
+  }
```
Comment (alanshaw) [inline test/install.js]: Let this throw? The test won't pass if this fails right?

File: test/install.js [hunk 4]
```diff
@@ -0,0 +1,43 @@
...
+const rimraf = require('rimraf')
+
+/*
+  Test that go-ipfs is downloaded during npm install.
+  - package up the current source code with `npm pack`
+  - install the tarball into the example project
+  - ensure that the "go-ipfs.version" prop in the package.json is used
+*/
+
+const testVersion = 'v0.4.21-rc3'
```
Comment (alanshaw) [inline test/install.js]: Read from the fixture?

File: test/install.js [hunk 5]
```diff
@@ -0,0 +1,43 @@
...
+    console.error(err)
+  }
+}
+
+test.onFinish(() => {
+  fs.unlinkSync(path.join(__dirname, tarballName))
+})
+
+test('Ensure go-ipfs.version defined in parent package.json is used', async (t) => {
+  rimraf.sync(path.join('fixture', 'example-project', 'node_modules'))
```
Comment (alanshaw) [inline test/install.js]: Move to `onFinish`?

File: test/install.js [hunk 6]
```diff
@@ -0,0 +1,40 @@
...
+  tarballName = res.stdout
+  return tarballName
+}
+
+test.onFinish(() => {
+  fs.unlinkSync(path.join(__dirname, tarballName))
+  rimraf.sync(path.join('fixture', 'example-project', 'node_modules'))
+})
+
+test.only('Ensure go-ipfs.version defined in parent package.json is used', (t) => {
```
Comment (alanshaw) [inline test/install.js]: .only
